# Generated by Django 4.0.4 on 2022-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vend_email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vend_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
