# Generated by Django 4.0.5 on 2022-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminmaster_cart_order_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='vend_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
