# Generated by Django 4.0.5 on 2022-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_ap_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='rg_status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
