# Generated by Django 4.0.5 on 2022-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_register_rg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ps_or_id', models.CharField(max_length=100)),
                ('ps_product_name', models.CharField(max_length=100)),
                ('ps_image', models.CharField(max_length=100)),
                ('ps_weight', models.CharField(max_length=100)),
                ('ps_price', models.CharField(max_length=100)),
                ('ps_total_amt', models.CharField(max_length=100)),
                ('ps_date', models.CharField(max_length=100)),
                ('ps_status', models.CharField(max_length=100)),
                ('ps_user_name', models.CharField(max_length=100)),
                ('ps_user_email', models.CharField(max_length=100)),
                ('ps_vendor_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='rg_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
